apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mfab
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0059-tenant/tkrw-pr712-0075-0059-app/devfile-sample-mfab@sha256:f9059ac101286aed8d112e148629ec9ca2e553265ae1d1bfd51069f13f8db3c9
        name: my-nodejs
        resources: {}
status: {}
